# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scaffolder}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Barton"]
  s.date = %q{2010-11-24}
  s.description = %q{Organise sequence contigs into genome scaffolds using simple human-readable YAML files.}
  s.email = %q{mail@michaelbarton.me.uk}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/scaffolder.rb",
    "lib/scaffolder/errors.rb",
    "lib/scaffolder/region.rb",
    "lib/scaffolder/region/insert.rb",
    "lib/scaffolder/region/sequence.rb",
    "lib/scaffolder/region/unresolved.rb",
    "scaffolder.gemspec",
    "test/helper.rb",
    "test/test_insert.rb",
    "test/test_region.rb",
    "test/test_scaffolder.rb",
    "test/test_sequence.rb",
    "test/test_unresolved.rb",
    "yard/attribute_handler.rb"
  ]
  s.homepage = %q{http://www.michaelbarton.me.uk/scaffolder/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Genome scaffolding for human beings.}
  s.test_files = [
    "test/helper.rb",
    "test/test_insert.rb",
    "test/test_region.rb",
    "test/test_scaffolder.rb",
    "test/test_sequence.rb",
    "test/test_unresolved.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 0"])
      s.add_development_dependency(%q<mocha>, ["~> 0.8"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<redgreen>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<bio>, [">= 0"])
      s.add_dependency(%q<mocha>, ["~> 0.8"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<redgreen>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<bio>, [">= 0"])
    s.add_dependency(%q<mocha>, ["~> 0.8"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<redgreen>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

